const GRAPHEION_SUPABASE_URL = "https://mgpzpufkohrbkvzauvty.supabase.co";
const GRAPHEION_SUPABASE_PUBLISHABLE_KEY = "sb_publishable_6SOLGYnVD5XCTk5w-MAQdA_KHXf_kN7";

export const SUPABASE_URL = GRAPHEION_SUPABASE_URL;

export const SUPABASE_PUBLISHABLE_KEY = GRAPHEION_SUPABASE_PUBLISHABLE_KEY;
